version: '3.7'

services:

  starter:
    image: ${DOCKER_REGISTRY:-docker.io}/olegabu/fabric-tools-extended:${FABRIC_STARTER_VERSION:-latest}
    container_name: starter
    environment:
      - ORG
      - DOMAIN
      - DOCKER_REGISTRY
      - FABRIC_STARTER_HOME
      - ENROLL_ID
      - ENROLL_SECRET
      - BOOTSTRAP_IP
      - MY_IP
      - AGENT_MODE
    command: sh -c 'docker-compose -f docker-compose-this-folder.yaml -f /etc/hyperledger/container-scripts/dns/consul-dns.yaml up --force-recreate -d; docker-compose -f docker-compose.yaml -f docker-compose-api-port.yaml --env-file=./crypto-config/dns/dns-env up --force-recreate api'
    volumes:
      - ${FABRIC_STARTER_HOME:-.}/crypto-config:/etc/hyperledger/crypto-config
      - /var/run/docker.sock:/var/run/docker.sock



networks:
  default:
    external: false
    name: fabric-starter_default

