#
# Copyright . All Rights Reserved.
#

version: '3.7'

services:
  cli.clean:
    container_name: cli.clean
#    build:
#      args:
#        FABRIC_VERSION: ${FABRIC_VERSION:-latest}
#      context: ./fabric-tools-extended
    image: ${DOCKER_REGISTRY:-docker.io}/olegabu/fabric-tools-extended:${FABRIC_VERSION:-latest}
    working_dir: /etc/hyperledger
    volumes:
    - /var/run/:/host/var/run/
    - ./crypto-config:/etc/hyperledger/crypto-config


  cli.bft:
    container_name: bft.cli.${ORG:-org1}
    image: ${DOCKER_REGISTRY:-docker.io}/bftsmart/fabric-tools:amd64-${FABRIC_VERSION:-1.3.0}
    working_dir: /etc/hyperledger
    volumes:
      - ./crypto-config:/etc/hyperledger/crypto-config
      - ./templates:/etc/hyperledger/templates
