version: '3.7'

services:

  consul-agent-1: &consul-agent
    image: consul:latest
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server -client 0.0.0.0"

  consul-server-bootstrap:
    <<: *consul-agent
    container_name: consul-server
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=yes
#    networks:
#      default:
#      test:
#        ipv4_address: 172.16.0.100

    ports:
      - "8400:8400"
      - "${CONSUL_SERVER_PORT:-8500}:8500"
      - "8600:53"
      - "8600:53/udp"
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0 -dns-port 53"
    volumes:
      - ./data/dns:/dns

#  dns-server-determiner:
#    image:
#    command: echo DNS_SERVER=`host consul-server | grep -Po '\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}'` > /dns/env

  dns-registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    command: consul://consul-server:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

networks:
  default:
    external: false
    name: fabric-starter_default

  test:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
