version: '3.7'

services:

  consul-server-first:
    image: consul:latest
    container_name: consul-server
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=yes
    ports:
      - "8400:8400"
      - "${CONSUL_UI_PORT:-8500}:8500"
#      - "8600:53"
#      - "8600:53/udp"
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0 -dns-port 53 -advertise ${MY_IP}"

  consul-server: &consul-server
    image: consul:latest
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=yes
    ports:
      - "8400:8400"
      - "${CONSUL_UI_PORT:-8500}:8500"
    command: "agent -server -retry-join ${BOOTSTRAP_IP} -client 0.0.0.0 -dns-port 53 -advertise ${MY_IP}"

  dns-server-ip:
    image: ${DOCKER_REGISTRY:-docker.io}/olegabu/fabric-tools-extended:${FABRIC_STARTER_VERSION:-latest}
    container_name: dns-server-ip
    entrypoint: []
    command: /bin/sh -c 'echo DNS_SERVER=`getent ahostsv4 consul-server | head -n 1 | grep -Po "\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}"` > /dns/env'
    volumes:
      - ./data/dns:/dns
    depends_on:
      - consul-server-first

  dns-registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    command: consul://consul-server:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

networks:
  default:
    external: false
    name: fabric-starter_default

