#
# Copyright . All Rights Reserved.
#

version: '3.7'


services:

#
  peer0:
    ports:
      - ${PEER0_PORT:-7051}:${PEER0_PORT:-7051}

  # simple http server to disseminate certificates
  www.peer:
    environment:
      - ORG=${ORG:-org1}
      - DOMAIN=${DOMAIN:-example.com}
    ports:
      - ${API_PORT:-4000}:4000
      - ${WWW_PORT:-80}:80
    command: bash -c "while [ ! -f /templates/nginx.conf ];do echo 'Wait for /templates/nginx.conf'; sleep 1;done; sleep 5; envsubst '$$ORG $$DOMAIN' < /templates/nginx.conf > /etc/nginx/conf.d/default.conf && cp /certs/${ORG}.${DOMAIN}/* /etc/nginx/conf.d/ && nginx -g 'daemon off;'"
    volumes:
      - ${SSL_CERTS_PATH:-./https/certs}:/certs
      - ./crypto-config/templates:/templates:ro
    depends_on:
      - certs.generate
      - api

