version: '3.7'

services:

  consul-agent:
    image: ${DOCKER_REGISTRY:-docker.io}/consul:latest
    container_name: consul-agent-${CONSUL_UI_PORT:-8500}
    restart: always
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=yes
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "${CONSUL_UI_PORT:-8500}:8500"
    #      - "8600:53"
    #      - "8600:53/udp"
    entrypoint: ""
    command: sh -c "if [[ -z '${BOOTSTRAP_IP}' && '${AGENT_MODE}' != 'client' ]]; then /usr/local/bin/docker-entrypoint.sh agent -ui -client 0.0.0.0 -dns-port 53 -server -bootstrap-expect 1 -advertise ${MY_IP}; fi;
      if [[ -n '${BOOTSTRAP_IP}' && '${AGENT_MODE}' != 'client' ]]; then /usr/local/bin/docker-entrypoint.sh agent -ui -client 0.0.0.0 -dns-port 53 -server -retry-join ${BOOTSTRAP_IP} -advertise ${MY_IP}; fi;
      if [ '${AGENT_MODE}' = 'client' ]; then /usr/local/bin/docker-entrypoint.sh agent -ui -retry-join ${BOOTSTRAP_IP} -client 0.0.0.0 -dns-port 53 -advertise ${MY_IP}; fi"

  #  -advertise ${MY_IP}


  dns-registrator:
    image: ${DOCKER_REGISTRY:-docker.io}/gliderlabs/registrator:latest
    container_name: registrator
    restart: always
    command: -retry-attempts 10 -ip ${MY_IP} consul://consul-agent-${CONSUL_UI_PORT:-8500}:8500
    depends_on:
      - consul-agent
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  dns-ip-domain:
    image: ${DOCKER_REGISTRY:-docker.io}/olegabu/fabric-tools-extended:${FABRIC_STARTER_VERSION:-latest}
    container_name: dns-ip-domain
    environment:
      - DOMAIN=${DOMAIN:-example.com}
    command: /bin/sh -c 'set -x; echo DOMAIN_SUFFIX=$${DOMAIN##*.}\\nDOMAIN_PREFIX=$${DOMAIN%.*}\\nDNS_SERVER=`getent ahostsv4 consul-agent-${CONSUL_UI_PORT:-8500} | head -n 1 | grep -Po "\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}"` > /dns/dns-env'
    volumes:
      - ${FABRIC_STARTER_HOME:-.}/crypto-config/dns:/dns
    depends_on:
      - consul-agent


networks:
  default:
    external: false
    name: fabric-starter_default

